[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "anki"
version = "0.0.1"
authors = [
	{ name="Это вы!", email="i_nikotin@thegame.design" }
]
description = "Игра Карты Anki"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"pytest"
]


[project.scripts]
anki = "anki.main:main"

